//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Master_Details.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SaleDetail
    {
        public long SaleDetailId { get; set; }
        public Nullable<long> SaleId { get; set; }
        public string ProductName { get; set; }
        public Nullable<decimal> Qty { get; set; }
        public Nullable<decimal> Price { get; set; }
    
        public virtual SaleMaster SaleMaster { get; set; }
    }
}
